import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default [
  js.configs.recommended,
  prettier,
  {
    rules: {
      'no-unused-vars': ['warn', { args: 'none', vars: 'local' }],
      'no-redeclare': 'off',
      'no-console': 'off',
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.browser,
        supabase: 'readonly',
        L: 'readonly',
        lucide: 'readonly',
        db: 'readonly',
        loadDays: 'readonly',
        loadMembers: 'readonly',
        ensureMemberSelected: 'readonly',
        el: 'readonly',
        append: 'readonly',
        formatTimeAgo: 'readonly',
        haversineKm: 'readonly',
        renderSidebar: 'readonly',
        renderMap: 'readonly',
        goTo: 'readonly',
        initApp: 'readonly',
        initStatsWidget: 'readonly',
        setActive: 'readonly',
        enterDetail: 'readonly',
        exitDetail: 'readonly',
        renderDayDetail: 'readonly',
        renderPlaceMap: 'readonly',
        focusPlace: 'readonly',
        deletePlaceHandler: 'readonly',
        initRealtime: 'readonly',
        initPlaceRealtime: 'readonly',
        handleDayChange: 'readonly',
        handlePlaceChange: 'readonly',
        showServerUpdatedIndicator: 'readonly',
        openEditor: 'readonly',
        closeEditor: 'readonly',
        saveEditor: 'readonly',
        openPlaceEditor: 'readonly',
        closePlaceEditor: 'readonly',
        savePlaceEditor: 'readonly',
        searchPlaceHandler: 'readonly',
        enablePlacePickMode: 'readonly',
        placePickHandler: 'readonly',
        renderSplitCheckboxes: 'readonly',
        openConflictModal: 'readonly',
        closeConflictModal: 'readonly',
        initAuth: 'readonly',
        loadDayPlaces: 'readonly',
        addPlace: 'readonly',
        updatePlace: 'readonly',
        deletePlace: 'readonly',
        searchPlaceName: 'readonly',
        reverseGeocodePlace: 'readonly',
        fetchPlaceImage: 'readonly',
        fetchDayBoundary: 'readonly',
        fetchPlaceThumbnail: 'readonly',
        DAYS: 'writable',
        map: 'writable',
        markers: 'writable',
        curIdx: 'writable',
        places: 'writable',
        placeMarkers: 'writable',
        placePolylines: 'writable',
        placeBoundaryLayer: 'writable',
        isDetailMode: 'writable',
        detailDayIndex: 'writable',
        SUPABASE_URL: 'readonly',
        SUPABASE_ANON_KEY: 'readonly',
        TRIP_ITINERARY_ID: 'readonly',
        TRIP_DEPARTURE_DATE: 'readonly',
      },
    },
  },
  {
    ignores: ['config.js'],
  },
];
